github: @FabianaCampanari
['https://github.com/FabianaCampanari',
'https://github.com/FabianaCampanari/Fashion-and-Design']
open_collective: @FabianaCampanari
['https://opencollective.com/fabianacampanari',
'https://opencollective.com/fabianacampanari/projects/fashion-and-design']
