# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [@FabianaCampanari]
open_collective: # Replace with a single Open Collective username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://github.com/FabianaCampanari/Fashion-and-Design']
